---
title: "S1st_pfactor_effect_continuous"
author: "Xiaoyu xu"
date: "4/17/2024"
output: html_document
---

This script is to eveluate associations between p-factor and SC strength using GAMMs in the ABCD dataset.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mgcv)
library(parallel)
library(tidyverse)
library(reshape)
library(RColorBrewer)
rm(list = ls())
CVthr=75
wdpath <- getwd()
if (str_detect(wdpath, "cuizaixu_lab")){
  interfileFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/interdataFolder_ABCD'
  functionFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/Rcode_SCdevelopment/gamfunction'
  resultFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/results_ABCD'
  
}else{
  resultFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/results_ABCD'
  interfileFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/interdataFolder_ABCD'
  functionFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
  FigureFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Figure_ABCD_final/SA12/CV75'
  source(paste0(functionFolder, "/SCrankcorr.R"))
}

# source function
source(paste0(functionFolder, '/gamminteraction.R'))
detectCores()
# load data
SCdata<-readRDS(paste0(interfileFolder, '/SCdata_SA12_CV', CVthr,'_sumSCinvnode.sum.msmtcsd.combatPFactorGeneral.rds'))
SCdata[,c("sex", "handness", "race_ethnicity")] <- lapply(SCdata[,c("sex", "handness", "race_ethnicity")], as.factor)
SCdata$age <- SCdata$age / 12
SCdata$totalstrength <- rowMeans(SCdata[,str_detect(names(SCdata), "SC.") & str_detect(names(SCdata), "_h")])
summary(SCdata$totalstrength)
SA12_10 <- read.csv(paste0(interfileFolder, '/SA12_10.csv'))
plotdata <- readRDS(paste0(interfileFolder, '/plotdatasum.df_SA12_sumSCinvnode_siteall_CV', CVthr,'.rds'))
# scale the SC strength by their initial strength in the age span
SCdata.diw <- SCdata
for (x in 1:78){
  region <- grep("SC.", names(SCdata), value = T)[x]
  plotdata.tmp <- plotdata[plotdata$SC_label==paste0("SC.", x, "_h"), ]
  SCstrength.diw <- SCdata[,region] / plotdata.tmp$fit[1]
  SCdata.diw[,region] <- SCstrength.diw
}
SCdata.diw[,grep("SC.", names(SCdata), value = T)] <- lapply(SCdata.diw[,grep("SC.", names(SCdata), value = T)], as.numeric)
SCdata.diw[,c("sex", "handness")] <- lapply(SCdata.diw[,c("sex", "handness")], as.factor)
meandistance <- read.csv(paste0(interfileFolder, "/average_EuclideanDistance_12.csv"))
meandistance <- meandistance$Edistance

```

## 1. p-factor association

```{r pfactor_T}
dataname <- "SCdata"
smooth_var <- "age" 
int_var.predict.percentile=0.1
covariates <- "sex+mean_fd" 
knots=3
set_fx = TRUE
increments = 1000
stats_only=TRUE
int_var <- "GENERAL"
if (str_detect(wdpath, "cuizaixu_lab")){
  resultsum <- mclapply(1:78, function(x){
    region <- grep("SC.", names(SCdata), value=T)[x]
    gamresult <- gamm.smooth.predict.covariateinteraction(region, dataname, smooth_var, int_var, int_var.predict.percentile, covariates, knots, set_fx, increments, stats_only)
    gamresult <- as.data.frame(gamresult)

    return(gamresult)
  }, mc.cores = 50)
  gamresult.tmp <- do.call(rbind, resultsum)
  gamresult.tmp[3:12] <- lapply(gamresult.tmp[3:12], as.numeric)
  gamresult.tmp$bootstrap_pvalue.fdr <- p.adjust(gamresult.tmp$bootstrap_pvalue, method = "fdr")
  gamresult.tmp$bootstrap.P.disease.fdr <- p.adjust(gamresult.tmp$bootstrap.P.disease, method = "fdr")

  print(paste0(sum(gamresult.tmp$bootstrap_pvalue.fdr<0.05), " edges have significant age by ", int_var, " effect."))
  print(paste0(sum(gamresult.tmp$bootstrap.P.disease.fdr<0.05), " edges have significant ", int_var, " effect."))

  saveRDS(gamresult.tmp, paste0(interfileFolder, "/gamresult_Int_age_pFactor_", int_var, "_CV", CVthr, ".rds"))
}

# Correlation to connectional axis
gamresult.tmp <- readRDS(paste0(interfileFolder, "/gamresult_Int_age_pFactor_", int_var, "_CV", CVthr,".rds"))
gamresult.tmp[3:12] <- lapply(gamresult.tmp[3:12], as.numeric)
print(paste0(sum(gamresult.tmp$bootstrap_pvalue.fdr<0.05), " edges have significant age by ", int_var, " effect."))
gamresult.tmp$bootstrap.P.disease.fdr <- p.adjust(gamresult.tmp$bootstrap.P.disease, method = "fdr")
print(paste0(sum(gamresult.tmp$bootstrap.P.disease.fdr<0.05), " edges have significant ", int_var, " effect."))
# CV75: 11 edges have significant general effect.
SCrank.df.age <- SCrankcorr(gamresult.tmp, "IntpartialRsq", 12, dsdata=FALSE)
SCrank.df.general <- SCrankcorr(gamresult.tmp, "T.disease", 12, dsdata=FALSE)
SCrank.df <- rbind(SCrank.df.age, SCrank.df.general)
SCrank.df$int_var <- int_var
SCrank.df
SCrank.tmp <- SCrankcorr(gamresult.tmp, "IntpartialRsq", 12, dsdata=T)
SCrank <- SCrank.tmp$SCrank

print("Next, correlation between psychopathological associations and connectional axis is tested while controlling for Euclidean distance.")
gamresult.tmp$meandistance <- meandistance
corr.test(gamresult.tmp$T.disease, gamresult.tmp$meandistance, method = "pearson")
gamresult.tmp$T.disease_control_distance[which(!is.na(gamresult.tmp$T.disease))] <- residuals(lm(T.disease~meandistance, data=gamresult.tmp))
corr.test(gamresult.tmp$T.disease_control_distance, gamresult.tmp$meandistance, method = "pearson") # r=0
SCrankresult.whole.controldistance <- SCrankcorr(gamresult.tmp, "T.disease_control_distance", 12, dsdata=FALSE)
print(paste("Correlation coefficient between cognitve associations regressing out fiber distance and connectional axis is", round(SCrankresult.whole.controldistance$r.spearman,2), "with a P value of", round(SCrankresult.whole.controldistance$p.spearman,3)))
print(SCrankresult.whole.controldistance)


```

## 2. scatter polts & matrix graph


```{r scatter_plot}

for (Interest.var in c("IntpartialRsq", "T.disease", "T.disease_control_distance")){
  tmpvar <- gamresult.tmp[,Interest.var]
  limthr <- max(abs(gamresult.tmp[,Interest.var]), na.rm=T)
  if (str_detect(Interest.var, "T.disease") & int_var=="GENERAL"){
    ytitle=expression(italic("p")*"-factor association ("*italic("T")*" value)")
  }else{ytitle=Interest.var}
  print(Interest.var)
  if (str_detect(Interest.var, "_control_distance")){
    mytheme <- theme(axis.text=element_text(size=23, color="black"), 
          axis.title =element_text(size=23),aspect.ratio = 0.97,
          axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
          plot.title = element_text(size=20, hjust = 0.5, vjust=2),
          plot.background=element_rect(fill="transparent"),
          panel.background=element_rect(fill="transparent"),
          legend.position = "none")
    mywidth=13
    myheight=13
  }else{
    mytheme <- theme(axis.text=element_text(size=23.4, color="black"), 
        axis.title =element_text(size=23.4),aspect.ratio = 1,
        axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
        plot.title = element_text(size=20, hjust = 0.5, vjust=2),
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        legend.position = "none")
    mywidth=15
    myheight=15}
  
  # scatter plot
  scatterFig <- ggplot(data=gamresult.tmp)+
    geom_point(aes(x=SCrank, y=tmpvar, color=tmpvar), size=5)+
    geom_smooth(aes(x=SCrank, y=tmpvar),linewidth=1.4, method ="lm", color="black")+
    scale_color_distiller(type="seq", palette = "RdBu", direction = -1, limits=c(-limthr, limthr))+
    labs(x="S-A connectional axis rank", y=ytitle)+
    theme_classic()+
    mytheme
  print(scatterFig)
  ggsave(paste0(FigureFolder, '/Disease/pFactor/',Interest.var, '_',int_var,'_SCrankcorr.tiff'),scatterFig, width=mywidth, height =myheight, units = "cm")
  ggsave(paste0(FigureFolder, '/Disease/pFactor/',Interest.var, '_',int_var,'_SCrankcorr.svg'),scatterFig, dpi=600,width=mywidth, height =myheight, units = "cm")
  
  # matrix
  Matrix.tmp.T <- matrix(NA,12,12)
  Matrix.tmp.T[lower.tri(Matrix.tmp.T, diag = T)] <- tmpvar
  Matrix.tmp.T[upper.tri(Matrix.tmp.T)] <- t(Matrix.tmp.T)[upper.tri(Matrix.tmp.T)]
  colnames(Matrix.tmp.T) <-seq(1, 12)
  rownames(Matrix.tmp.T) <-seq(1, 12)
  matrixtmp.df <- as.data.frame(Matrix.tmp.T)
  matrixtmp.df$nodeid <- seq(1, 12)
  matrixtmp.df.melt <- melt(matrixtmp.df,id.vars=c("nodeid"))
  matrixtmp.df.melt$variable<-as.numeric(matrixtmp.df.melt$variable)
  matrixtmp.df.melt$nodeid<-0-matrixtmp.df.melt$nodeid
  matrixtmp.df.melt$value<-as.numeric(matrixtmp.df.melt$value)
  
  Matrix.tmp.sig <- matrix(NA,12,12)
  if (Interest.var=="IntpartialRsq"){
    Matrix.tmp.sig[lower.tri(Matrix.tmp.sig, diag = T)] <- (gamresult.tmp$bootstrap_pvalue.fdr < 0.05)
  }else{
    Matrix.tmp.sig[lower.tri(Matrix.tmp.sig, diag = T)] <- (gamresult.tmp$bootstrap.P.disease.fdr < 0.05)
  }
  
  Matrix.tmp.sig[upper.tri(Matrix.tmp.sig)] <- t(Matrix.tmp.sig)[upper.tri(Matrix.tmp.sig)]
  colnames(Matrix.tmp.sig) <-seq(1, 12)
  rownames(Matrix.tmp.sig) <-seq(1, 12)
  matrixtmp.df.sig <- as.data.frame(Matrix.tmp.sig)
  matrixtmp.df.sig$nodeid <- seq(1, 12)
  matrixtmp.df.sig.melt <- melt(matrixtmp.df.sig,id.vars=c("nodeid"))
  matrixtmp.df.sig.melt$variable<-as.numeric(matrixtmp.df.sig.melt$variable)
  matrixtmp.df.sig.melt$nodeid<-0-matrixtmp.df.sig.melt$nodeid
  matrixtmp.df.sig.melt$value<-as.numeric(matrixtmp.df.sig.melt$value)
  matrixtmp.df.sig.melt <- matrixtmp.df.sig.melt[-which(matrixtmp.df.sig.melt$value==0),]
  titlematrix <- paste0(int_var, "_", Interest.var)
  linerange_frame<-data.frame(x=c(0.5,12+0.5), ymin =rep(-12-0.5, times=2), ymax =rep(-0.5, times=2),
                              y=c(-0.5, -12-0.5), xmin=rep(0.5, times=2), xmax=rep(12+0.5, times=2))
  
  MatFig<-ggplot(data =matrixtmp.df.melt)+
    geom_tile(aes(x=variable, y=nodeid, fill = value, color=value))+
    scale_fill_distiller(type="seq", palette = "RdBu",na.value = "grey", limits=c(-limthr, limthr))+
    scale_color_distiller(type="seq", palette = "RdBu",na.value = "grey", limits=c(-limthr, limthr))+
    geom_text(data =matrixtmp.df.sig.melt, aes(x=variable, y=nodeid, label = "*"), vjust = 0.7, hjust = 0.5, size=8)+
    geom_linerange(data=linerange_frame, aes(y=y, xmin =xmin, xmax =xmax), color="black", linewidth=0.5)+
    geom_linerange(data=linerange_frame, aes(x=x, ymin =ymin, ymax =ymax), color="black", linewidth=0.5)+
    geom_segment(aes(x = 0.5 , y = -0.5 , xend = 12+0.5 ,yend = -12-0.5), color="black", linewidth=0.5)+
    ggtitle(label = titlematrix)+labs(x=NULL, y=NULL)+
    scale_y_continuous(breaks=NULL, labels = NULL)+
    scale_x_continuous(breaks=NULL, labels = NULL)+
    theme(axis.line = element_blank(),
          #axis.ticks=element_line(linewidth = 0),
          axis.text.x=element_text(size=12, angle=45, hjust=1),
          axis.text.y=element_text(size=12, angle=315, hjust=1,vjust=1),
          axis.title =element_text(size=18),
          plot.title = element_text(size=12, hjust = 0.5),
          legend.title=element_text(size=18),
          legend.text=element_text(size=18),
          panel.background=element_rect(fill=NA),
          panel.grid.major=element_line(linewidth = 0),
          panel.grid.minor=element_line(linewidth = 1))
  print(MatFig)
  filename<-paste0(FigureFolder, '/Disease/pFactor/',Interest.var, '_',int_var,'_Matrix12.tiff')
  ggsave(filename, MatFig,  height = 18, width = 20, units = "cm")
  
}

```

## 3. Ineraction plot
Developmental trajectories by different levels of p-factor.
```{r SCdev_by_pfactor}
dataname <- "SCdata.diw"
int_var <- "GENERAL"
stats_only <- FALSE

if (exists(paste0(interfileFolder, '/plotdata_high90_low10_pFactor_', int_var, '_develop_CV',CVthr ,'.rds'))==0){
  resultsum <- list()
  for (x in 1:78){
    int_var.predict.percentile <- 0.1
    region <- grep("SC.", names(SCdata.diw), value=T)[x]
    result.all <- gamm.smooth.predict.covariateinteraction(region, dataname, smooth_var, int_var, int_var.predict.percentile, covariates, knots, set_fx, increments, stats_only)
    plotdata.low <- result.all[[2]]
    plotdata.low$pFactor <- int_var
    plotdata.low$label <- "low"
    
    int_var.predict.percentile <- 0.9
    result.all <- gamm.smooth.predict.covariateinteraction(region, dataname, smooth_var, int_var, int_var.predict.percentile, covariates, knots, set_fx, increments, stats_only)
    plotdata.high <- result.all[[2]]
    plotdata.high$pFactor <- int_var
    plotdata.high$label <- "high"
    
    plotdata <- rbind(plotdata.low, plotdata.high)
    plotdata$SC_label <- region
    
    resultsum[[x]] <- plotdata
  }
  saveRDS(resultsum, paste0(interfileFolder, '/plotdata_high90_low10_pFactor_', int_var, '_develop_CV',CVthr ,'.rds'))
  
}
resultsum <- readRDS(paste0(interfileFolder, '/plotdata_high90_low10_pFactor_', int_var, '_develop_CV',CVthr ,'.rds'))
plotdata <- do.call(rbind, resultsum)
plotdata <- merge(plotdata, SA12_10, by="SC_label")

plotdf.decile.low <- plotdata %>% filter(label=="low") %>% 
  group_by(decile, age) %>%
  summarise(fit.avg = mean(.fitted), decile=mean(decile))
plotdf.decile.low$label <- "low"

plotdf.decile.high <- plotdata %>% filter(label=="high") %>% 
  group_by(decile, age) %>%
  summarise(fit.avg = mean(.fitted), decile=mean(decile))
plotdf.decile.high$label <- "high"

plotdf.decile <- rbind(plotdf.decile.low, plotdf.decile.high)


colorid <- rev(brewer.pal(10, "RdBu"))
for (i in 1:10){
  plotdf.tmp <- plotdf.decile[plotdf.decile$decile==i,]
  colorindex <- colorid[i]
  age_label_mult <- if (max(plotdf.tmp$age, na.rm = TRUE) <= 2) 10 else 1
  if (i == 1 | i ==6){
    mytheme=theme(axis.text=element_text(size=21, color="black"), 
                  axis.title =element_text(size=21),aspect.ratio = 1,
                  axis.line = element_line(linewidth=0.5),axis.ticks = element_line(linewidth=0.5),
                  plot.background=element_rect(fill="transparent"),
                  panel.border = element_rect(fill=NA, color="transparent"),
                  panel.background=element_rect(fill="transparent", color="transparent"), legend.position = "none")
    
  }else{
    mytheme=theme(axis.text.x =element_text(size=21, color="black"), 
                  axis.text.y =element_text(size=21, color="transparent"),
                  axis.title.x =element_text(size=21),
                  axis.title.y =element_text(size=21, colour = "transparent"),
                  aspect.ratio = 1,
                  axis.line.x = element_line(linewidth=0.5), 
                  axis.line.y = element_line(linewidth=0.5, colour = "transparent"),
                  axis.ticks.x = element_line(linewidth=0.5),
                  axis.ticks.y = element_line(linewidth=0.5, colour = "transparent"),
                  plot.background=element_rect(fill="transparent"),
                  panel.grid=element_line(linewidth=0.5, colour = "transparent"),
                  panel.border = element_rect(fill=NA, color="transparent"),
                  panel.background=element_rect(fill="transparent", color="transparent"), legend.position = "none")
    
  }
  # high (abnormal) is dashed; low (normal) is solid
  Fig <- ggplot(data=plotdf.tmp)+
    geom_line(aes(x=age, y=fit.avg, group=label, linetype=label),linewidth=1.2, color=colorindex)+
    scale_x_continuous(labels = function(x) x * age_label_mult)+
    scale_y_continuous(breaks = c(0.9, 1.0), limits=c(0.90, 1.1))+
    scale_linetype_manual(values=c("dashed", "solid"))+
    labs(x=NULL, y="SC strength (ratio)")+
    mytheme
  ggsave(paste0(FigureFolder, '/Disease/pFactor/Interaction/developmentcurve_decile', i, '.tiff'),Fig, width = 10, height = 10, units = "cm")
  ggsave(paste0(FigureFolder, '/Disease/pFactor/Interaction/developmentcurve_decile', i, '.svg'),Fig, width = 10, height = 10, units = "cm")
}


```




