---
title: "S3rd_visualizationfitSCcurves_SA12suminvnode_HBN"
output: html_document
date: "2024-11-07"
---

This script is to generate fitted values from gam models. The predicted SC strength will be generated as the age was sampled from 5 to 22, with a total of 1000 data points, covariables will be set as median or mode.The data will be used to draw developmental trajectories. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R.matlab)
library(mgcv)
library(psych)
library(tidyverse)
library(parallel)
library(scales)
library(openxlsx)
library(gratia)
library(ggplot2)
library(RColorBrewer)
library(paletteer)
library(patchwork)
rm(list = ls())

demopath<-'D:/xuxiaoyu/open_dataset_information/HBN/demography'
interfileFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/interdataFolder_HBN'
FigureFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Figure_HBN_final/SA12/CV75/TractSeg'
functionFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
resultFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/results_HBN'

```

## 1. load data & function

```{r load_data}
#### load data
CVthr = 75
gamresultsum.SAorder.delLM<-readRDS(paste0(interfileFolder, '/gamresults78_sumSCinvnode_TractSeg_CV', CVthr,'_scale_TRUE.rds'))
gammodelsum<-readRDS(paste0(interfileFolder, '/gammodel78_sumSCinvnode_CV', CVthr,'_scale_TRUE.rds'))
SCdata <- readRDS(paste0(interfileFolder, '/SCdata_SA12_CV', CVthr,'_sumSCinvnode.TractSeg.combatage.rds'))
derivative <- readRDS(paste0(resultFolder, '/derivative.df78_TractSeg_CV', CVthr,'.rds'))
#### source function
source(paste0(functionFolder, '/plotdata_generate.R'))
source(paste0(functionFolder, '/colorbarvalue.R'))
source(paste0(functionFolder, '/SCrankcorr.R'))
#### generate fitted values for developmental trajectories
agevector=SCdata$age
# set cluster

plotdatasum<-list()
for (x in 1:78){
  modobj<-gammodelsum[[x]]
  plotdata<- plotdata_generate(modobj,dataname=NA, "age", agevector)
  plotdatasum[[x]] <- plotdata
}
saveRDS(plotdatasum, paste0(interfileFolder, "/plotdatasum_scale_TRUE_SA12_TractSeg.rds"))

plotdatasum.df <- do.call(rbind, lapply(plotdatasum, function(x){
  x$SC_label <- names(x)[14]
  x <- x[,-14]
  return(x)
}))

#### SA12 index & SC rank
rand.df <- data.frame(rnorm=rnorm(78,0,1))
SCrankdf <- SCrankcorr(rand.df, "rnorm", 12, T)
SCrankdf$SC_label <- paste0(1:78, "_h")
plotdatasum.df <- plotdatasum.df %>% left_join(SCrankdf, by="SC_label") %>% left_join(gamresultsum.SAorder.delLM, join_by(SC_label==parcel))


```

## Plots

### 2 Developmental trajectories.

```{r plot_trajectory1}
lmthr <- max(abs(gamresultsum.SAorder.delLM$partialRsq))
ggplot()+
  geom_line(data=plotdatasum.df, aes(x=age, y=fit.ratio, group=SC_label, color=partialRsq), size=0.8, alpha=0.8)+
  scale_color_distiller(type="seq", palette = "RdBu",direction = -1, limit=c(-lmthr,lmthr))+
  labs(x="Age (years)", y="SC strength (ratio)")+
  theme_classic()+
  theme(axis.text=element_text(size=22, color="black"), 
        axis.title =element_text(size=22, color="black"),aspect.ratio = 0.9,
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        plot.title = element_text(size=15, hjust = 0.5), legend.position = "none")

ggsave(paste0(FigureFolder,  '/SA12_sumSCinvnode_fit/devcurve_Rsq_fit.ratio.tiff'), width=20, height =14, units = "cm")
ggsave(paste0(FigureFolder,  '/SA12_sumSCinvnode_fit/devcurve_Rsq_fit.ratio.svg'), dpi=600, width=15, height =15, units = "cm")
```

```{r plot_trajectory2}
gamresultsum.SAorder.delLM <- gamresultsum.SAorder.delLM %>% mutate(
  meanderv2_c = case_when(
    meanderv2 < mean(meanderv2)-3*sd(meanderv2) ~ NA,
    .default = meanderv2
  )
)
limthr <- max(abs(gamresultsum.SAorder.delLM$meanderv2_c), na.rm = T)
SC_label_derv2_order <- gamresultsum.SAorder.delLM$parcel[order(gamresultsum.SAorder.delLM$meanderv2)]
plotdatasum.df$SC_label2 <- factor(plotdatasum.df$SC_label, levels=SC_label_derv2_order)
plotdatasum.df <- plotdatasum.df %>% left_join(select(gamresultsum.SAorder.delLM, c("parcel", "meanderv2_c")), join_by(SC_label==parcel))
ggplot()+
  geom_line(data=plotdatasum.df, aes(x=age, y=fit.Z, group=SC_label2, color=meanderv2_c), size=0.8, alpha=0.8)+
  #paletteer::scale_color_paletteer_c("pals::ocean.matter", direction = -1, values=colorbarvalues.meanderiv2, oob = squish) +
  scale_color_distiller(type="seq", palette = "RdBu",limits=c(-limthr, limthr),na.value ="#053061", direction = -1)+
  labs(x="Age (years)", y="SC strength (z-score)")+
  #scale_color_manual(values = rev(brewer.pal(10, "RdBu")))+
  scale_y_continuous(breaks = c(-1.5, 0.0, 1.5))+
  theme_classic()+
  theme(axis.text=element_text(size=22, color="black"), 
        axis.title =element_text(size=22, color="black"),aspect.ratio = 0.9,
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        plot.title = element_text(size=15, hjust = 0.5), legend.position = "none")

ggsave(paste0(FigureFolder,  '/SA12_sumSCinvnode_fit/devcurve_meanderv2_fit.Z.tiff'), width=20, height =14, units = "cm")
ggsave(paste0(FigureFolder, '/SA12_sumSCinvnode_fit/devcurve_meanderv2_fit.Z.svg'), dpi=600, width=15, height =15, units = "cm")

```


