---
title: "S1st_SAcorr_alongAge_ABCD"
author: "Xiaoyu xu"
date: "4/16/2024"
output: html_document
---

This script is to generate the alignment between 1st derivatives and S-A connectional axis. Derivatives and posterior derivatives generated will be used. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(R.matlab)
library(psych)
library(gratia)
library(mgcv)
library(parallel)
library(ggplot2)
library(RColorBrewer)
library(reshape)

rm(list = ls())
wdpath <- getwd()
CVthr = 75
if (str_detect(wdpath, "cuizaixu_lab")){
  interfileFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/interdataFolder_ABCD'
  functionFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/Rcode_SCdevelopment/gamfunction'
  resultFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/results_ABCD'
  
}else{
  resultFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/results_ABCD'
  interfileFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/interdataFolder_ABCD'
  functionFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
  FigureFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Figure_ABCD_final/SA12'
}
derivative.posterior.df <- readRDS(paste0(resultFolder, '/derivative.posterior.df.SA12_CV', CVthr,'.rds'))
derivative.df <- readRDS(paste0(resultFolder, '/derivative.df78_CV', CVthr,'.rds'))
#### source function
source(paste0(functionFolder, '/gamderivatives.R'))
source(paste0(functionFolder, '/colorbarvalue.R'))
source(paste0(functionFolder, "/SCrankcorr.R"))
#### calculate S-A connectional axis in 12*12
########################
Matrix12<-matrix(NA, nrow=12, ncol=12)
indexup12 <- upper.tri(Matrix12)
indexsave12 <- !indexup12
Matrix12.index<-Matrix12
#13*12/2=78
Matrix12.index[indexsave12]<-c(1:78)
Matrix12.SCrank<-Matrix12
for (x in 1:12){
  for (y in 1:12){
    Matrix12.SCrank[x,y]<-x^2+y^2
  }
}
Matrix12.SCrank[indexup12]<-NA
SCrank12<-rank(Matrix12.SCrank[indexsave12], ties.method = "average")

```

## 1. calculate correlation between posterior derivatives and S-A connectional axis

```{r compute_correlation}
deri.SCrank.posterior.diw.corr <- data.frame(matrix(NA, 1000, 1000))
rownames(deri.SCrank.posterior.diw.corr) <- paste0("draw.", c(1:1000))
colnames(deri.SCrank.posterior.diw.corr) <- paste0("age.", c(1:1000))
# define function
compute.SC.corr <- function(drawtime){
  deriv.SA12.drawtmp <- data.frame(age=rep(NA, 78*1000), deri.pos=rep(NA, 78*1000),
                                   SClabel=rep(NA, 78*1000))
  for (i in 1:78){
    df.tmp <- derivative.posterior.df[[i]]
    df.tmp <- df.tmp[df.tmp$draw==paste0("draw", drawtime),]
    lwth <- (i-1)*1000 +1
    upth <- i*1000
    deriv.SA12.drawtmp$age[lwth:upth]<-df.tmp$age
    deriv.SA12.drawtmp$deri.pos[lwth:upth]<-df.tmp$posterior.derivative
    deriv.SA12.drawtmp$SClabel[lwth:upth]<-paste0("SC.", i)
  }
  agerange <- deriv.SA12.drawtmp$age[1:1000]
  corr.df <- data.frame(corr.pos.tmp=rep(NA,1000))
  # estimate rho at 1,000 age points
  for (j in 1:1000){
    deri.pos.tmp <- deriv.SA12.drawtmp$deri.pos[deriv.SA12.drawtmp$age==agerange[j]]
    corr.pos.tmp <- corr.test(deri.pos.tmp, SCrank12, method = "spearman")$r
    corr.df$corr.pos.tmp[j]<-corr.pos.tmp
  }
  rownames(corr.df) <- paste0("age.", agerange)
  return(corr.df)
}

# compute correlation coefficients between S-A connectional axis and 1,000 posterior derivatives at 1,000 age points.
if (str_detect(wdpath, "cuizaixu_lab")){
  deri.SCrank.posterior.corr.sum<-mclapply(1:1000, function(x){
  corr.df.tmp <- compute.SC.corr(x)
  return(corr.df.tmp)
}, mc.cores = 50)

deri.SCrank.posterior.corr<-do.call(rbind, lapply(deri.SCrank.posterior.corr.sum, function(x) t(x$corr.pos.tmp)))
deri.SCrank.posterior.corr<-as.data.frame(deri.SCrank.posterior.corr)
write.csv(deri.SCrank.posterior.corr, paste0(resultFolder, '/deri.SCrank12_CV', CVthr,'.posterior.diw.corr.csv'), row.names = F)
}else{
  deri.SCrank.posterior.corr <- read.csv(paste0(resultFolder, '/deri.SCrank12_CV', CVthr,'.posterior.diw.corr.csv'))
}
agerange <- unique(derivative.posterior.df[[1]]$age)
#### median corr and 95% CI
# diw
posterior.corr.diw.median <- lapply(c(1:1000), function(x) median(round(deri.SCrank.posterior.corr[,x],4)))
posterior.corr.diw.median <- as.numeric(unlist(posterior.corr.diw.median))
# diw 95%CI
posterior.corr.diw.CI <- lapply(c(1:1000), function(x) quantile(round(deri.SCrank.posterior.corr[,x],4), probs=c(0.025, 0.975)))
posterior.corr.diw.CI <- do.call(rbind, lapply(posterior.corr.diw.CI, function(x) data.frame(t(x))))

```


## 2. plot alignment with S-A connectional axis correlation
```{r plotalignment}
df.poscorr.diw <- data.frame(age=agerange, median=posterior.corr.diw.median, up.95CI=posterior.corr.diw.CI$X97.5.,
                             lw.95CI=posterior.corr.diw.CI$X2.5.)
loess.median <- loess(median~age, data=df.poscorr.diw, span=0.2)
loess.lw <- loess(lw.95CI~age, data=df.poscorr.diw, span=0.2)
loess.up <- loess(up.95CI~age, data=df.poscorr.diw, span=0.2)
df.poscorr.diw$median.loess <- loess.median$fitted
df.poscorr.diw$lw.95CI.loess <- loess.lw$fitted
df.poscorr.diw$up.95CI.loess <- loess.up$fitted

mytheme <- theme(axis.text=element_text(size=23, color="black"), 
        axis.title =element_text(size=23),aspect.ratio = 1,
        axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
        plot.title = element_text(size=20, hjust = 0.5, vjust=2),
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        legend.position = "none")

ggplot(data=df.poscorr.diw)+
  geom_ribbon(aes(x=age, ymin=lw.95CI.loess, ymax=up.95CI.loess), alpha=0.3)+
  geom_line(aes(x=age, y=median.loess), size=1.5)+
  scale_y_continuous(breaks=c(-0.6, -0.3, 0.0))+
  theme_classic()+
  labs(x="Age (years)", y="rho")+
  mytheme
ggsave(paste0(FigureFolder,'/CV', CVthr, '/Alignment_development/SA12_posDeriv_divweight_corr.tiff'), width=13.5, height=13.5, units="cm")
ggsave(paste0(FigureFolder,'/CV', CVthr,  '/Alignment_development/SA12_posDeriv_divweight_corr.svg'), width=16, height=14, units="cm")

```

## 3.correlation plot at different age
```{r plot_sep_age}
agerange <- unique(derivative.df$age)
df.poscorr.diw$median[df.poscorr.diw$age==min(agerange)]
# age = 8.083333
min(agerange)
df.age8 <-as.data.frame(matrix(NA, nrow=1, ncol=9))
names(df.age8)<-names(derivative.df)
for (i in 1:78){
  df.tmp <- derivative.df[derivative.df$label_ID==paste0("SC.", i, "_h"),]
  df.tmp <- df.tmp[df.tmp$age==min(agerange), ]
  df.age8 <- rbind(df.age8, df.tmp)
}
df.age8 <- df.age8[-1,]

SCrankcorr(df.age8, "derivative", 12) 

df.poscorr.diw$age[which.min(abs(df.poscorr.diw$median-0))]
ntmp<-which.min(abs(agerange-max(agerange))) 
agerange[ntmp]
df.age13 <-as.data.frame(matrix(NA, nrow=1, ncol=9))
names(df.age13)<-names(derivative.df)
for (i in 1:78){
  df.tmp <- derivative.df[derivative.df$label_ID==paste0("SC.", i, "_h"),]
  df.tmp <- df.tmp[df.tmp$age==agerange[ntmp], ]
  df.age13 <- rbind(df.age13, df.tmp)
}
df.age13 <- df.age13[-1,]
SCrankcorr(df.age13, "derivative", 12) 


## display 3 lines in one plot, Fig. S6F.
df.agemerge <- rbind(df.age8, df.age13)
df.agemerge$age <- as.factor(df.agemerge$age)
ggplot(data=df.agemerge)+
  geom_smooth(aes(x=rep(SCrank12, 2), y=derivative, group=age), linewidth=1.2,color="black", method ="lm", 
              se=T)+
  #scale_y_continuous(breaks=c(-0.02, 0, 0.02), labels=c(-2,0,2))+
  labs(x="S-A connectional axis rank", y="SC change rate")+
  theme_classic()+
  theme(axis.text=element_text(size=24.8, color="black"), 
        axis.title =element_text(size=24.8),aspect.ratio = 0.97,
        plot.title = element_text(size=15, hjust = 0.1, vjust=-5),
        axis.line = element_line(linewidth=0.55), axis.ticks = element_line(linewidth=0.55),
        legend.position = "none", plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"))
ggsave(paste0(FigureFolder,'/CV', CVthr,  '/Alignment_development/deri.diw_corr_SCrank12ageAll.tiff'), width = 16, height = 14, units="cm")
ggsave(paste0(FigureFolder,'/CV', CVthr,  '/Alignment_development/deri.diw_corr_SCrank12ageAll.svg'), dpi=600, width = 16, height = 14, units="cm")
#############################################

### derivative plots
##################################
SCrank <- data.frame(label_ID=paste0("SC.",c(1:78), "_h"), SCrank12=SCrank12)
SCrank$SCrank12 <- rank(SCrank$SCrank12, ties.method = "first")
derivative.df.merge <- merge(derivative.df, SCrank, by="label_ID", all.x=T)

## line plot to present change rate.
ggplot(data=derivative.df.merge)+
  geom_line(aes(x=age, y=derivative, group=label_ID, color=SCrank12),size=1.4, alpha=1)+
  scale_color_distiller(type="seq", palette = "RdBu")+
  scale_fill_distiller(type="seq", palette = "RdBu")+
  #geom_vline(xintercept = c(8.92, 13.75), linetype=2, size=0.5)+
  scale_y_continuous(limits=c(-0.075, 0.07), breaks=c(-0.05, 0, 0.05), labels=c(-5,0,5))+
  labs(x="Age (years)", y="SC change rate", color="Axis rank")+
  theme_classic()+
  theme(axis.text=element_text(size=23, color="black"), 
        axis.title =element_text(size=23),aspect.ratio = 1.2,
        plot.title = element_text(size=15, hjust = 0.5),
        axis.line = element_line(linewidth=0.5),axis.ticks = element_line(linewidth=0.5),
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        legend.position = "none")
ggsave(paste0(FigureFolder,'/CV', CVthr,  '/Alignment_development/derivative_diw_SA12_changerate.tiff'), width = 20, height = 16, units="cm")
ggsave(paste0(FigureFolder,'/CV', CVthr,  '/Alignment_development/derivative_diw_SA12_changerate.svg'), width = 13, height = 13, units="cm")
write.csv(derivative.df.merge, paste0(interfileFolder, '/derivative_df_12_merge_CV', CVthr,'.csv'), row.names = F)

### mean derivative matrix at different age
#############################################
minderiv <- min(c(df.age8$derivative, df.age13$derivative))
maxderiv <- max(c(df.age8$derivative, df.age13$derivative))
valuesderiv <- colorbarvalues(seq(minderiv, maxderiv, length.out=100), 0.6)
linerange_frame<-data.frame(x=c(0.5,12+0.5), ymin =rep(-12-0.5, times=2), ymax =rep(-0.5, times=2),
                            y=c(-0.5, -12-0.5), xmin=rep(0.5, times=2), xmax=rep(12+0.5, times=2))

# age 8
Matsize <- 12
matrix_Deriv.age8 <- Matrix12
matrix_Deriv.age8[indexsave12] <- df.age8$derivative
matrix_Deriv.age8[indexup12] <- t(matrix_Deriv.age8)[indexup12]
colnames(matrix_Deriv.age8) <-seq(1, Matsize)
rownames(matrix_Deriv.age8) <-seq(1, Matsize)
matrix_Deriv.age8.df <- as.data.frame(matrix_Deriv.age8)
matrix_Deriv.age8.df$nodeid <- seq(1, Matsize)
matrix_Deriv.age8.df.melt <- melt(matrix_Deriv.age8.df,id.vars=c("nodeid"))
matrix_Deriv.age8.df.melt$variable<-as.numeric(matrix_Deriv.age8.df.melt$variable)
matrix_Deriv.age8.df.melt$nodeid<-0-matrix_Deriv.age8.df.melt$nodeid
ggplot(data =matrix_Deriv.age8.df.melt)+
  geom_tile(aes(x=variable, y=nodeid, fill = value, color=value))+
  scale_fill_distiller(type="seq", palette = "RdBu",limit=c(minderiv, maxderiv), values=valuesderiv)+
  scale_color_distiller(type="seq", palette = "RdBu",limit=c(minderiv, maxderiv), values=valuesderiv)+
  geom_segment(aes(x = 0.5 , y = -0.5 , xend = Matsize+0.5 ,yend = -0.5-Matsize), color="black", linewidth=0.5)+
  geom_linerange(data=linerange_frame, aes(y=y, xmin =xmin, xmax =xmax), color="black", linewidth=0.5)+
  geom_linerange(data=linerange_frame, aes(x=x, ymin =ymin, ymax =ymax), color="black", linewidth=0.5)+
  ggtitle(label = "Age = 8.9")+
  labs(x="", y="")+
  scale_y_continuous(breaks=NULL, labels = NULL)+
  scale_x_continuous(breaks=NULL, labels = NULL)+
  theme(axis.line = element_line(linewidth = 0), 
        #axis.ticks=element_line(linewidth = 0),
        axis.text.x=element_text(size=20), 
        axis.text.y=element_text(size=20),
        axis.title =element_text(size=20),
        plot.title = element_text(size=20, hjust = 0.5),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20), 
        panel.background=element_rect(fill=NA),
        panel.grid.major=element_line(linewidth = 0), 
        panel.grid.minor=element_line(linewidth = 1))
ggsave(paste0(FigureFolder,'/CV', CVthr,   '/Alignment_development/Deri_SA12_diw_age8.tiff'),  height = 13, width = 15, units = "cm")

# age 13
Matsize <- 12
matrix_Deriv.age13 <- Matrix12
matrix_Deriv.age13[indexsave12] <- df.age13$derivative
matrix_Deriv.age13[indexup12] <- t(matrix_Deriv.age13)[indexup12]
colnames(matrix_Deriv.age13) <-seq(1, Matsize)
rownames(matrix_Deriv.age13) <-seq(1, Matsize)
matrix_Deriv.age13.df <- as.data.frame(matrix_Deriv.age13)
matrix_Deriv.age13.df$nodeid <- seq(1, Matsize)
matrix_Deriv.age13.df.melt <- melt(matrix_Deriv.age13.df,id.vars=c("nodeid"))
matrix_Deriv.age13.df.melt$variable<-as.numeric(matrix_Deriv.age13.df.melt$variable)
matrix_Deriv.age13.df.melt$nodeid<-0-matrix_Deriv.age13.df.melt$nodeid
ggplot(data =matrix_Deriv.age13.df.melt)+
  geom_tile(aes(x=variable, y=nodeid, fill = value, color=value))+
  scale_fill_distiller(type="seq", palette = "RdBu",limit=c(minderiv, maxderiv), values=valuesderiv)+
  scale_color_distiller(type="seq", palette = "RdBu",limit=c(minderiv, maxderiv), values=valuesderiv)+
  geom_segment(aes(x = 0.5 , y = -0.5 , xend = Matsize+0.5 ,yend = -0.5-Matsize), color="black", linewidth=0.5)+
  geom_linerange(data=linerange_frame, aes(y=y, xmin =xmin, xmax =xmax), color="black", linewidth=0.5)+
  geom_linerange(data=linerange_frame, aes(x=x, ymin =ymin, ymax =ymax), color="black", linewidth=0.5)+
  ggtitle(label = "Age = 13.6")+
  labs(x="", y="")+
  scale_y_continuous(breaks=NULL, labels = NULL)+
  scale_x_continuous(breaks=NULL, labels = NULL)+
  theme(axis.line = element_line(linewidth = 0), 
        #axis.ticks=element_line(linewidth = 0),
        axis.text.x=element_text(size=20), 
        axis.text.y=element_text(size=20),
        axis.title =element_text(size=20),
        plot.title = element_text(size=20, hjust = 0.5),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20), 
        panel.background=element_rect(fill=NA),
        panel.grid.major=element_line(linewidth = 0), 
        panel.grid.minor=element_line(linewidth = 1))
ggsave(paste0(FigureFolder,'/CV', CVthr,   '/Alignment_development/Deri_SA12_diw_age13.tiff'),  height = 13, width = 15, units = "cm")

```
